apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:iBhFKzA22HL3YvF54HGOI2L61RhJ/FQzGLo4LGekT7NA3gbEYkkDlAvWAfIz0h8MhSfCDipIewu5U8nS+D1MRLBMvRjcLYvzP+SWpmbhWSjHJO04CPZ1mkcen1brLQ4/DZCDuPK0trFoF8MolAIwW5T9ktIoSkn9V01EoptxC2bcYvkd8Ysk25JJ5e0DAnvZhEdzicyB8zMbQThcGqgPkpmnVVrRTY9Da0PWgp/rf1g5ntV1xGiL8x/T8TO4OBbx8p38h6h6RSaolDTtaTQ0hwwxA/QBWYwwQchJ/MbUIBicszjkbwi3MYLAJJc=,iv:vaj8zLmGEU+rkv9JRRwQendbzaYBtgkC1mCjVpusOWM=,tag:MP1uEVK81ZeaOiVtsmNfMg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd1I4OStqYTNxQjNoYy9y
            cmJlYWo2Tko0VWorWDROZGtnTmZxUFJNcWhBCmNVdFY5NTVwYlpra3oxZzMrTjRm
            aUg3dEc5L0tOQ05TTDZzbWJVUEk2VTAKLS0tIEJsNVRPQ3NNVEJPWStoNnpvajZR
            a3hsSitIZnlPK2JubWZqNWtGQWhQZFEKA/RD7IjRBSdl2gqB4KTYnIt0BSi003kd
            KPd+rfzhSgU3spR6/TrgwLtONMTr2zpui83gViRTW9KuQImn4LfKHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yyj38ks5yu7fm95xach4ja0y45r8axcv2jypz3u7w5lrcxsgquyssx29rz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T13:18:14Z"
    mac: ENC[AES256_GCM,data:QBt6cyAZ5lirBnyhgALM5w80WpGp9J+dmRGFW6FTirL2RfSDlbnavrMc/5s9VJaF4uh2s3zP4rt6m93TYC5lyrxMaChAeuv2+TIBpkhfhATZtB10rpzt0dKp+Zn/Jfy+xXODXwlOPYTF6IpVxWaw9pwjIWuGAxnVQLiKj2sbR64=,iv:gmKItTCijoj/nf+HPVxW0xLBRFaR4SKCcOifSS/uoz8=,tag:FZV4GY+3Crl/yBfhpUR8OQ==,type:str]
    version: 3.13.3
