apiVersion: v1
data:
    FRESHRSS_USER: ENC[AES256_GCM,data:QOgm3jMFKkwzYFDETYk8pjklRHE7VNk5JreVYO1bFRGbKKJuRWuKQV8XSwTAb+NEfp2NrrYY3uIbMKY7f2kMiY6AJetQdD+wSesqxC74et3FyeXQXZgTT5UrBBf+wfD8RzsmyNU07wLTMrz7ggcfSq0/59+JPMZz,iv:xLUWIB0wp+Li+zWMgpTSUve8xE4tOumqui7CbNe27Ss=,tag:0K/BvUp8u5JVYbO5OIEQog==,type:str]
kind: Secret
metadata:
    name: freshrss-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVDY3bytNakxNZ0hDazdv
            c2UxanNNdVBnMmFMYWhEbkMyS1pBYVc0SzFzCmtqR0FjUDhrV2ppekdWeFZvSlJJ
            LytRS0dBdGEzNkgxOHZXbk02bTRJOXMKLS0tIGtzRWNtZVJjSnZHZVpPZDhrSyta
            YzJNWkNTQWZ5MHFFNzVpTi9aQkN5UjgKFOfZxlwaDpRE2Hx2w7eYRdueiuEWmK3K
            tsh0P7RrPRRHExBzJh4OU/fsIIfEPUAEEuWb86hA17ET7PtAZVnakA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yyj38ks5yu7fm95xach4ja0y45r8axcv2jypz3u7w5lrcxsgquyssx29rz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T13:18:14Z"
    mac: ENC[AES256_GCM,data:Un1Pu6xJFhk3QJA9gT2y03CMskWkEeat7s5/KwYdClJfIKL/uY+kk4Vq9oufTzLOcekP+UC0eEqQFAqmghOqdpfppcnRWgFwrJgsvmBDwdSs/ARUeZIkKpG/6Z9GmZqc+Gbd+wgAT9YnciFY06uAN7ASKrU3aC+E4h+LyeKUAH4=,iv:zRXkjP/XTcS2rGKoUkBUz0Wtt79yiftPhTOhrxObUsU=,tag:Qxwizj69hA5ACVO8EHo3GA==,type:str]
    version: 3.13.3
