apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:0FYv7+FzrkDw+O0fWriiA2wHKw6IUGlPwyXp/yGVy86grFC7TA5K+wQfQRDKv7U+1VdSWgi/HYY7sQ2Nu+RIy11NFJ1obJmPVahZu9SA8hfgnAPGZeKrRMp2/wFCqNelBNWWNBeib1HiRIi10WFQ0WDD5R9Oo1vM33SmcphJ5DU485dp+rMjzSn1mv6muIbXfhMkevtjSXpUlk7RG6a+KeHNUU4VqY8wembVw1AOh9pRQ/Aw8iK7ySlP4F7Vl6QIooLTzLXD8D9EsnypQ46PzTYg6FOkf3Oe1uv0PbdCthpHGYB1akz+ak1kug8=,iv:NtqCOl3X7VISjR44YvzOJ6i0ijueXVkVdT+TDzV0G20=,tag:JLBqoGLSk2ytr1BWZe7wCg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1yyj38ks5yu7fm95xach4ja0y45r8axcv2jypz3u7w5lrcxsgquyssx29rz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUXVpUEE2d2hZOHg4TjVj
            dCsySXdDODNRQjdGc2EzdWVEcHNwVFY3SEZZCjA2RVNMRWY3M1NJcUpLRFpNeFho
            Vjk4anFobFJkWjliTTN5TVp0ZWpGUjgKLS0tIFlhdDBFRnExZjdkNTB5VFNXb1BX
            L1pYWTNkUWo0ZWZQM2phekt6amhZZFUKaXqZAKJfCy9TYUpphjcOCmIkOm/RzI6c
            t9noXDjo5EykYM4gBugZPjBC82jKq6yfpcoM/G5Jp0/rw6lTyZVt8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T00:24:28Z"
    mac: ENC[AES256_GCM,data:cQL87FP2+gsHWzKbicUPmjfKngiU5eGvxFfJbm+jkNLPeyBc87mKCk3uGCwhDOvmKTpgMIoBhJsddpmAQzgORKnqqzNTcFc/4IJnJMKn81xNBz40cCte16viqqBvlfWtOHDINcb/Z7mAgdQy5G37nWC3wSl0s+yGv4HjUEeBdzU=,iv:IIjvoIHJzEcxkeDxC+t6AUIoC5jcw/X2KMk3jgMvMyA=,tag:S8YiRvscuYJ6STBjQwiGwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
