apiVersion: v1
kind: Secret
metadata:
    name: vikunja-move-log
type: Opaque
stringData:
    VIKUNJA_TOKEN: ENC[AES256_GCM,data:kL1kte7kSWcpsLNYPKwY7VcAc+4JgRcHWH8kBHBXjYT1oq1gOzpoFYIVfQ==,iv:5x4zGl0J4hOeeB/M+GyGTjtn/cVMEe+TXj8FCfCR/Pg=,tag:i+oVPlCOangOLnp9w3zbkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNXhQeEV1c2xNYi9DRDFB
            Y1ZlbEVuYmFIQXJMNnNQRVNQeXNhUDdtYXhjCnJNWmNvd21weTlzV1Aza2kvcUxQ
            QlVVcjdQVTZNdnd6YXR2aElpQXJoRW8KLS0tIDlxMWY3a3k5SUI1NFM5L3FVQXR3
            MXlzQ1VLUW9UK2R5MGVyV1paV2NWdUUK3DgRTMrg2Nzez8oN+lh0KJKQbRxkrlm2
            LUHdgt0wfnhCYdBKz3STa3l8FikGKtE8EbkD2oHOxT7FAvUn+76UDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yyj38ks5yu7fm95xach4ja0y45r8axcv2jypz3u7w5lrcxsgquyssx29rz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T15:07:30Z"
    mac: ENC[AES256_GCM,data:eJoF8+iWMgnBhz1cPta2Fj3ihaHHAOK24Zz1SHvRRHuB8nTijX0cLbygqd+6JvkMjLa0R+F3EsAbg9QGNEVQzNyRkzjxlGBcEOy6MPWYT28FzCSGZAPzUoMCaTam7tJm4JN8qerO6CTE+rOBe1re+wLpByp8dzmozRG0UHzs4q8=,iv:jKGXXiuALmt1cAOfKtWarecChZOSwZgDRPXIQyNfVZ0=,tag:XcfG27LE2wU1ZdVDvKq2UQ==,type:str]
    version: 3.13.3
