apiVersion: v1
data:
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:YpuWScxDY/k21c5E3MUWlD+Wqh2+xfWNhhZbgjpDUX8TZkR1iZir95X+C6z6pvrElQSIJOR/f1zyEZA6QDrTDFJp011sLWcWhJdu79J4xdslQZ4jctLx2A==,iv:B5dqSyGS3rE+TRrTfbzEuZM25OedUNAX1MHx15LfULg=,tag:nrGHauPU7gGkH40ylN5tWg==,type:str]
kind: Secret
metadata:
    name: vikunja-env
sops:
    age:
        - recipient: age1yyj38ks5yu7fm95xach4ja0y45r8axcv2jypz3u7w5lrcxsgquyssx29rz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUHpNWjdaQ2ZIbk0xellB
            WHo3SXdmNSt1QkllVmFuVThhU3pEZEVZUmlNCitWVzZRYWlNdFBMUFh4aHIzOC9B
            S0FlMk90TjFrNjNFQ3h2UGlVM2Q5clUKLS0tIEtKUjRhVzZVZWpIbXJDbkQ1N3JZ
            U0VMY2pjLzJwaW04Vy92OTFTcDAxMG8Kj/9Qwb5gKhrO2jleycv+iqgKq/9v2XdL
            Ua+ssw4MOyB+wQzZJORNw1UpfuEDjN0zet6D5aniBnRwkyKTN1/d9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T00:24:28Z"
    mac: ENC[AES256_GCM,data:JegEnVMFQx4Gk9smg+TRkw+LYjBqg6VnAdxd2BRONS6Q2lJRBA97KixGPSnLwJVvbKgvFjQhyJ9P4lrrRIpRAavDXtCApFEsaoe9jdRXSoKcqZjBUfLa4GDy6VTACDzE71hcny1mD/KUPZouPuMtr9uGt4JWp95bcBmfgPDFW/k=,iv:bTNUhrdsYngUhjP99+l0xzX7Vc54qogTE+qNpbyVXMQ=,tag:xSzaTt3gvTL3karKUmYi8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
